#!/bin/sh -e

test "$GITBUCKET_DB_NAME"
test "$GITBUCKET_DB_USER"
test "$GITBUCKET_DB_PASSWORD"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE USER $GITBUCKET_DB_USER PASSWORD '$GITBUCKET_DB_PASSWORD';
CREATE DATABASE $GITBUCKET_DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE $GITBUCKET_DB_NAME TO $GITBUCKET_DB_USER;
EOSQL
