#!/bin/sh -e

# Initialize Mattermost database
# https://github.com/mattermost/mattermost-docker

test "$MATTERMOST_DB_NAME"
test "$MATTERMOST_DB_USER"
test "$MATTERMOST_DB_PASSWORD"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE USER $MATTERMOST_DB_USER PASSWORD '$MATTERMOST_DB_PASSWORD';
CREATE DATABASE $MATTERMOST_DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE $MATTERMOST_DB_NAME TO $MATTERMOST_DB_USER;
EOSQL
